### PR TITLE
Rework: Make MariaDB + ansible great again

### PR DESCRIPTION
**Pull request by donvipre**
- add role repo-mariadb dependency once needed
- add the possibility to manage databases
- add the possibility to manage users
- Rework: decide between different mysql packages
  - currently possible repositories are (with simple addition of more):
    - OS vendor delivered packages
    - MariaDB upstream delivered packages 10.2
- Polish: syntax on tasks/mysql_secure_installation.yml
- Fix: Linting test

## Reference
 - Resolves: #4

### CODE REVIEW

**Comment by donvipre** [comment]
@daniel-wtd : please check from your side if the repository selection procedure is now as it should be.

**Comment by daniel-schier** [comment]
@donvipre Is it ok for you, that I will push some suggestions to this branch?

Have found a way to simplifie/streamline the whole package naming thingy 😺

**Comment by donvipre** [comment]
Please do, likely as a new commit to this branch :)

**Comment by donvipre** [comment]
it seems that the defaults are not working for repo_mariadb 10.2 on centos7.4 latest packages
```
journalctl -u mariadb
-- Logs begin at Mi 2018-01-31 20:52:54 CET, end at Mi 2018-01-31 21:36:43 CET. --
Jan 31 21:36:12 centos7.local systemd[1]: Starting MariaDB 10.2.12 database server...
Jan 31 21:36:12 centos7.local mysqld[10498]: 2018-01-31 21:36:12 140072136710272 [Note] /usr/sbin/mysqld (mysqld 10.2.12-MariaDB) starting as process 10498 ...
Jan 31 21:36:12 centos7.local mysqld[10498]: 2018-01-31 21:36:12 140072136710272 [Warning] InnoDB: Using innodb_file_format is deprecated and the parameter may be removed in future releases. See http://dev.mysql
Jan 31 21:36:12 centos7.local mysqld[10498]: 2018-01-31 21:36:12 140072136710272 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
Jan 31 21:36:12 centos7.local mysqld[10498]: 2018-01-31 21:36:12 140072136710272 [Note] InnoDB: Uses event mutexes
Jan 31 21:36:12 centos7.local mysqld[10498]: 2018-01-31 21:36:12 140072136710272 [Note] InnoDB: Compressed tables use zlib 1.2.7
Jan 31 21:36:12 centos7.local mysqld[10498]: 2018-01-31 21:36:12 140072136710272 [Note] InnoDB: Using Linux native AIO
Jan 31 21:36:12 centos7.local mysqld[10498]: 2018-01-31 21:36:12 140072136710272 [Note] InnoDB: Number of pools: 1
Jan 31 21:36:12 centos7.local mysqld[10498]: 2018-01-31 21:36:12 140072136710272 [Note] InnoDB: Using SSE2 crc32 instructions
Jan 31 21:36:12 centos7.local mysqld[10498]: 2018-01-31 21:36:12 140072136710272 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
Jan 31 21:36:12 centos7.local mysqld[10498]: 2018-01-31 21:36:12 140072136710272 [Note] InnoDB: Completed initialization of buffer pool
Jan 31 21:36:12 centos7.local mysqld[10498]: 2018-01-31 21:36:12 140071376316160 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpri
Jan 31 21:36:12 centos7.local mysqld[10498]: 2018-01-31 21:36:12 140072136710272 [Note] InnoDB: Highest supported file format is Barracuda.
Jan 31 21:36:12 centos7.local mysqld[10498]: 2018-01-31 21:36:12 140072136710272 [Note] InnoDB: 128 out of 128 rollback segments are active.
Jan 31 21:36:12 centos7.local mysqld[10498]: 2018-01-31 21:36:12 140072136710272 [Note] InnoDB: Creating shared tablespace for temporary tables
Jan 31 21:36:12 centos7.local mysqld[10498]: 2018-01-31 21:36:12 140072136710272 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
Jan 31 21:36:12 centos7.local mysqld[10498]: 2018-01-31 21:36:12 140072136710272 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
Jan 31 21:36:12 centos7.local mysqld[10498]: 2018-01-31 21:36:12 140072136710272 [Note] InnoDB: Waiting for purge to start
Jan 31 21:36:12 centos7.local mysqld[10498]: 2018-01-31 21:36:12 140072136710272 [Note] InnoDB: 5.7.20 started; log sequence number 1619207
Jan 31 21:36:12 centos7.local mysqld[10498]: 2018-01-31 21:36:12 140072136710272 [Note] Plugin 'FEEDBACK' is disabled.
Jan 31 21:36:12 centos7.local mysqld[10498]: 2018-01-31 21:36:12 140071298660096 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
Jan 31 21:36:12 centos7.local mysqld[10498]: 2018-01-31 21:36:12 140071298660096 [Note] InnoDB: Buffer pool(s) load completed at 180131 21:36:12
Jan 31 21:36:12 centos7.local mysqld[10498]: 2018-01-31 21:36:12 140072136710272 [Note] Server socket created on IP: '127.0.0.1'.
Jan 31 21:36:12 centos7.local mysqld[10498]: 2018-01-31 21:36:12 140072135776000 [ERROR] mysqld: Can't create/write to file '/var/run/mariadb/mariadb.pid' (Errcode: 2 "No such file or directory")
Jan 31 21:36:12 centos7.local mysqld[10498]: 2018-01-31 21:36:12 140072135776000 [ERROR] Can't start server: can't create PID file: No such file or directory
Jan 31 21:36:12 centos7.local systemd[1]: mariadb.service: main process exited, code=exited, status=1/FAILURE
Jan 31 21:36:12 centos7.local systemd[1]: Failed to start MariaDB 10.2.12 database server.
Jan 31 21:36:12 centos7.local systemd[1]: Unit mariadb.service entered failed state.
Jan 31 21:36:12 centos7.local systemd[1]: mariadb.service failed.
```

**Comment by donvipre** [comment]
I'm fine with this pull request.
@daniel-wtd please review & merge if fine

**Review by dschier-wtd — APPROVED** [review]
Looks awesome from my side.
Maybe we can add some cool variables in the future.

**Pull request merged**
