### PR TITLE
Fix: add socket location variable

### PR DESCRIPTION
**Pull request by donvipre**
## Reference
 - Resolves: #6

### CODE REVIEW

**Review by dschier-wtd — COMMENTED** [review]
You may initialize the variable as empty.
So you can check, if it is set without having problems, that it is not initialized:

wtd_mariadb_socket: ""

**Review by dschier-wtd — CHANGES_REQUESTED** [review]
You may initialize the variable as empty.
So you can check, if it is set without having problems, that it is not initialized:

wtd_mariadb_socket: ""

**Comment by daniel-schier** [comment]
Or maybe I got you wrong ^^

If you mean, that this socket is enabled in all default installations, than I will approve. I am a bit confused right now.

If it is not enabled per default, we should set it empty and integrate it only, when needed.

**Comment by donvipre** [comment]
All 3 versions create a socket per default. I'm not sure if this even can be disabled.

**Comment by daniel-schier** [comment]
I see, I see 👍

**Review by dschier-wtd — APPROVED** [review]

**Pull request merged**
